added core-ml intern JD
skit-ai/job-descriptions pull request #4
Opened 2021-12-08 08:50 UTC by sanchit-ahuja

Added the intern JD. Mostly inspired from the core-ml engineer JD and some from Research fellow

2021-12-08 10:47 UTC, lepisma requested changes

2021-12-08 10:47 UTC, lepisma commented on machine-learning/core-ml-intern.md
> +# Machine Learning Research Intern
ML Intern, Core ML

2021-12-08 10:47 UTC, lepisma commented on machine-learning/core-ml-intern.md
> +# Machine Learning Research Intern
Also let's change the name of file also

2021-12-08 10:47 UTC, lepisma commented on machine-learning/core-ml-intern.md
> +We are looking for an ML Research intern for a duration of 5 months. As an intern, you will be working closely with the core-ml team. You will be involved in owning various product initiatives, creat
name and duration

2021-12-08 10:47 UTC, lepisma commented on machine-learning/core-ml-intern.md
> +Our team works closely with the research team, broadly on the topics such as Spoken Language Understanding, Speech Recognition, Paralinguistics and Response Production.
We don't have to say the team, we can make it like the person will work closely with our product and research teams etc.

2021-12-08 10:47 UTC, lepisma commented on machine-learning/core-ml-intern.md
> ++ Write research outcomes and publish documentations
We can remove this part. This intern will be more focused on product development work.

2021-12-08 10:47 UTC, lepisma commented on machine-learning/core-ml-intern.md
> ++ Write well-crafted programs at all levels of the system. This includes the
can remove this line .too much expectation from an intrern.

2021-12-08 10:47 UTC, lepisma commented on machine-learning/core-ml-intern.md
> ++ Good programming skills and ability to work with programs at all levels of a
Can also be specific and ask for good 'prototyping skills' too

2021-12-08 10:52 UTC, sanchit-ahuja commented on machine-learning/core-ml-intern.md
> +We are looking for an ML Research intern for a duration of 5 months. As an intern, you will be working closely with the core-ml team. You will be involved in owning various product initiatives, creat
Should we mention the duration (and also the tentative months) or is it flexible? Name as in?

2021-12-08 13:08 UTC, lepisma requested changes

2021-12-08 13:08 UTC, lepisma commented on machine-learning/core-ml-intern.md
> +We are looking for an ML Research intern for a duration of 5 months. As an intern, you will be working closely with the core-ml team. You will be involved in owning various product initiatives, creat
yes, flexible. can put starting month as immediate.

Name shold be 'ML Intern' and not 'ML Research Intern'

2021-12-09 05:26 UTC, lepisma requested changes

2021-12-09 05:26 UTC, lepisma commented on machine-learning/ml-intern-core-ml.md
> +level: ML Intern, Core ML
Level wrong

2021-12-09 05:26 UTC, lepisma commented on machine-learning/ml-intern-core-ml.md
> +We are looking for an ML Research intern for a duration of 5 months to join immediately (duration and date of joining are flexible). As an intern, you will be working closely with the product and res
Let's do 2 to 5 months instead of 5 months?

2021-12-09 05:29 UTC, sanchit-ahuja commented on machine-learning/ml-intern-core-ml.md
> +level: ML Intern, Core ML
What level to put? L1 or leave it NA?

2021-12-09 05:50 UTC, lepisma commented on machine-learning/ml-intern-core-ml.md
> +level: ML Intern, Core ML
NA

2021-12-09 07:56 UTC, merged